# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comp.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ncomp.proto\"\x12\n\x10TerminateRequest\"\"\n\x0eServerResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\"\x1a\n\x0bMainRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"G\n\x0cMainResponse\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0c\n\x04matr\x18\x02 \x01(\r\x12\r\n\x05\x63urso\x18\x03 \x01(\t\x12\x0c\n\x04\x63red\x18\x04 \x01(\x05\"\x1a\n\x0bSigaRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"*\n\x0cSigaResponse\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0c\n\x04matr\x18\x02 \x01(\r\" \n\x10MatriculaRequest\x12\x0c\n\x04matr\x18\x01 \x01(\r\"0\n\x11MatriculaResponse\x12\r\n\x05\x63urso\x18\x01 \x01(\t\x12\x0c\n\x04\x63red\x18\x02 \x01(\x05\x32\x62\n\x0bMainService\x12\"\n\x03Get\x12\x0c.MainRequest\x1a\r.MainResponse\x12/\n\tTerminate\x12\x11.TerminateRequest\x1a\x0f.ServerResponse2b\n\x0bSigaService\x12\"\n\x03Get\x12\x0c.SigaRequest\x1a\r.SigaResponse\x12/\n\tTerminate\x12\x11.TerminateRequest\x1a\x0f.ServerResponse2q\n\x10MatriculaService\x12,\n\x03Get\x12\x11.MatriculaRequest\x1a\x12.MatriculaResponse\x12/\n\tTerminate\x12\x11.TerminateRequest\x1a\x0f.ServerResponseb\x06proto3'
)




_TERMINATEREQUEST = _descriptor.Descriptor(
  name='TerminateRequest',
  full_name='TerminateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=32,
)


_SERVERRESPONSE = _descriptor.Descriptor(
  name='ServerResponse',
  full_name='ServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='ServerResponse.response', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=68,
)


_MAINREQUEST = _descriptor.Descriptor(
  name='MainRequest',
  full_name='MainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MainRequest.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=96,
)


_MAINRESPONSE = _descriptor.Descriptor(
  name='MainResponse',
  full_name='MainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='MainResponse.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matr', full_name='MainResponse.matr', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='curso', full_name='MainResponse.curso', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cred', full_name='MainResponse.cred', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=169,
)


_SIGAREQUEST = _descriptor.Descriptor(
  name='SigaRequest',
  full_name='SigaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='SigaRequest.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=197,
)


_SIGARESPONSE = _descriptor.Descriptor(
  name='SigaResponse',
  full_name='SigaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='SigaResponse.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matr', full_name='SigaResponse.matr', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=241,
)


_MATRICULAREQUEST = _descriptor.Descriptor(
  name='MatriculaRequest',
  full_name='MatriculaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='matr', full_name='MatriculaRequest.matr', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=275,
)


_MATRICULARESPONSE = _descriptor.Descriptor(
  name='MatriculaResponse',
  full_name='MatriculaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='curso', full_name='MatriculaResponse.curso', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cred', full_name='MatriculaResponse.cred', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=325,
)

DESCRIPTOR.message_types_by_name['TerminateRequest'] = _TERMINATEREQUEST
DESCRIPTOR.message_types_by_name['ServerResponse'] = _SERVERRESPONSE
DESCRIPTOR.message_types_by_name['MainRequest'] = _MAINREQUEST
DESCRIPTOR.message_types_by_name['MainResponse'] = _MAINRESPONSE
DESCRIPTOR.message_types_by_name['SigaRequest'] = _SIGAREQUEST
DESCRIPTOR.message_types_by_name['SigaResponse'] = _SIGARESPONSE
DESCRIPTOR.message_types_by_name['MatriculaRequest'] = _MATRICULAREQUEST
DESCRIPTOR.message_types_by_name['MatriculaResponse'] = _MATRICULARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TerminateRequest = _reflection.GeneratedProtocolMessageType('TerminateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TERMINATEREQUEST,
  '__module__' : 'comp_pb2'
  # @@protoc_insertion_point(class_scope:TerminateRequest)
  })
_sym_db.RegisterMessage(TerminateRequest)

ServerResponse = _reflection.GeneratedProtocolMessageType('ServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVERRESPONSE,
  '__module__' : 'comp_pb2'
  # @@protoc_insertion_point(class_scope:ServerResponse)
  })
_sym_db.RegisterMessage(ServerResponse)

MainRequest = _reflection.GeneratedProtocolMessageType('MainRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAINREQUEST,
  '__module__' : 'comp_pb2'
  # @@protoc_insertion_point(class_scope:MainRequest)
  })
_sym_db.RegisterMessage(MainRequest)

MainResponse = _reflection.GeneratedProtocolMessageType('MainResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAINRESPONSE,
  '__module__' : 'comp_pb2'
  # @@protoc_insertion_point(class_scope:MainResponse)
  })
_sym_db.RegisterMessage(MainResponse)

SigaRequest = _reflection.GeneratedProtocolMessageType('SigaRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGAREQUEST,
  '__module__' : 'comp_pb2'
  # @@protoc_insertion_point(class_scope:SigaRequest)
  })
_sym_db.RegisterMessage(SigaRequest)

SigaResponse = _reflection.GeneratedProtocolMessageType('SigaResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGARESPONSE,
  '__module__' : 'comp_pb2'
  # @@protoc_insertion_point(class_scope:SigaResponse)
  })
_sym_db.RegisterMessage(SigaResponse)

MatriculaRequest = _reflection.GeneratedProtocolMessageType('MatriculaRequest', (_message.Message,), {
  'DESCRIPTOR' : _MATRICULAREQUEST,
  '__module__' : 'comp_pb2'
  # @@protoc_insertion_point(class_scope:MatriculaRequest)
  })
_sym_db.RegisterMessage(MatriculaRequest)

MatriculaResponse = _reflection.GeneratedProtocolMessageType('MatriculaResponse', (_message.Message,), {
  'DESCRIPTOR' : _MATRICULARESPONSE,
  '__module__' : 'comp_pb2'
  # @@protoc_insertion_point(class_scope:MatriculaResponse)
  })
_sym_db.RegisterMessage(MatriculaResponse)



_MAINSERVICE = _descriptor.ServiceDescriptor(
  name='MainService',
  full_name='MainService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=327,
  serialized_end=425,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='MainService.Get',
    index=0,
    containing_service=None,
    input_type=_MAINREQUEST,
    output_type=_MAINRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Terminate',
    full_name='MainService.Terminate',
    index=1,
    containing_service=None,
    input_type=_TERMINATEREQUEST,
    output_type=_SERVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAINSERVICE)

DESCRIPTOR.services_by_name['MainService'] = _MAINSERVICE


_SIGASERVICE = _descriptor.ServiceDescriptor(
  name='SigaService',
  full_name='SigaService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=427,
  serialized_end=525,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='SigaService.Get',
    index=0,
    containing_service=None,
    input_type=_SIGAREQUEST,
    output_type=_SIGARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Terminate',
    full_name='SigaService.Terminate',
    index=1,
    containing_service=None,
    input_type=_TERMINATEREQUEST,
    output_type=_SERVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIGASERVICE)

DESCRIPTOR.services_by_name['SigaService'] = _SIGASERVICE


_MATRICULASERVICE = _descriptor.ServiceDescriptor(
  name='MatriculaService',
  full_name='MatriculaService',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=527,
  serialized_end=640,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='MatriculaService.Get',
    index=0,
    containing_service=None,
    input_type=_MATRICULAREQUEST,
    output_type=_MATRICULARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Terminate',
    full_name='MatriculaService.Terminate',
    index=1,
    containing_service=None,
    input_type=_TERMINATEREQUEST,
    output_type=_SERVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATRICULASERVICE)

DESCRIPTOR.services_by_name['MatriculaService'] = _MATRICULASERVICE

# @@protoc_insertion_point(module_scope)
